# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a6d6f96f652767738f08d3ffe68cdda2c720ee590932ac856af1dda2c127b966b3a915503a7a16bd80cb3892ea92e63f158963f54f5aa94f8b9061703668594

test:
  secret_key_base: 1d0c17261435268675ca0bbc3022453dbaaca6adecd8d19499e18f01e1a184553665a47338b3c57e7f0975d5d08072c762ac79004c06af2bdeac923e2b44e31a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
